### ISSUE TITLE
Looks nice and useful, could you add some licensing to it?

### ISSUE THREAD

**Issue by duchainer** [ivan-resetnikov/grappling-hook-3d#1]
Thanks for your work on that 👍 

If we want to allow using it in other projects, adding some permissive license to this repo, like the MIT license, would help greatly.

Let me know if you need help with that, but it would be some license option tab in your repo settings, from what I remember. 

Have a great week ^^

**Comment by ivan-resetnikov** [comment]
Hi, thanks for opening the issue.
I added two license files, one for GitHub, and one in the addon folder. Both are the same free and open source, MIT licenses
