### ISSUE TITLE
Conflicts with default installation structure

### ISSUE THREAD

**Issue by levidavidmurray** [ivan-resetnikov/grappling-hook-3d#2]
This addon looks super useful! Can't wait to give it a shot.

I just wanted to point out that it looks like the default installation structure is the entire project folder. I've never made a custom addon so I'm not sure of the solution. Maybe the plugin config subfolder isn't configured correctly?

![image](https://github.com/ivan-resetnikov/grappling-hook-3d/assets/46084870/89ff6c69-8b3c-4dfd-9c3f-59122706dbc2)

In any case, thanks for this!

**Comment by ivan-resetnikov** [comment]
Yes, that's an issue I noticed myself before. I'm going to look at other people's add-on repo's structure, and figure out the solution.

**Comment by ivan-resetnikov** [comment]
It seems that Godot does not have any metadata file format similar to `.gitignore` to specify files and directories that will be ignored during an install from the AssetLibrary in the engine. I will mark this a closed until this feature comes.

The solution for now would be to un-check the files that you do not want to come with the install.
