### ISSUE TITLE
node not appearing

### ISSUE THREAD

**Issue by zote-3** [ivan-resetnikov/grappling-hook-3d#3]
im using godot 4.2.2, and when i use the asset library to install your addon, the node isn't there when i try to add a new node, it is probably just meant for an older version but im gonna post it here just in case

**Comment by ivan-resetnikov** [comment]
Make sure that you did all the steps that usually come with installing a plugin in Godot.

1. After you've installed the plugin from the asset store - go to `Project > Project Settings > Plugins`, and enable the Grappling Hook 3D plugin. ![Make sure that it is enabled](https://github.com/ivan-resetnikov/grappling-hook-3d/assets/107191337/76f91607-aa74-4336-ad00-a6ea8574f911)

2. Then go to any scene to see if it works, and while focused on the node tree press `Ctrl + A` or just hit the `+` icon, and start typing "HookController". The node should appear there.

This was tested on Godot 4.2.2.

_On the side note - The steps above apply to other plugins as well so do not open as issue, unless there is an actual problem, not with Godot/You forgetting to do something but with the add-on._

Tell me if the steps above make the addon work for you.
